### ISSUE TITLE
Migrate `unstable_renderSubtreeIntoContainer` to ReactDOM.createPortal()

### ISSUE THREAD

**Issue by cjies** [iCHEF/gypcrete#79]
Switch from `unstable_renderSubtreeIntoContainer()` to `unstable_createPortal()` for compatibility with React Fiber.

Related informations:
- palantir/blueprint#1509
- [facebook/react#10309](https://github.com/facebook/react/issues/10309#issuecomment-318433235)

**Comment by cjies** [comment]
`ReactDOM.createPortal()` is official now :) facebook/react#10675

**Comment by cjies** [comment]
`unstable_renderSubtreeIntoContainer` do no work in enzyme v3... 😕

And portal components are not supported in enzyme yet. (airbnb/enzyme#252)

**Comment by cjies** [comment]
`enzyme-adpater-react-16` v1.1.0 starts to support React Portal.
https://github.com/airbnb/enzyme/commit/3ebc14a7982663d967e50072578321be068130d6#diff-c8bcb273fce5646f5438ffc519373594

Planning to upgrade React, Jest and Enzyme.

**Comment by zhusee2** [comment]
Addressed in #188.
