### ISSUE TITLE
Switch to Lerna

### ISSUE THREAD

**Issue by zhusee2** [iCHEF/gypcrete#85]
Split gypcrete into multiple packages but still maintain in one single repository.

**Comment by cjies** [comment]
Or trying [yarn workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/)?

**Comment by zhusee2** [comment]
They can work altogether to hoist packages, and it looks great

**Comment by zhusee2** [comment]
Issues after #87 is merged:
- [ ] Lerna failed to publish to NPM (probably because it can't read the NPM_TOKEN)
- [ ] Even when Lerna failed to publish, it exited with 0 and Travis took that as “success”.

**Comment by cjies** [comment]
[Simplest solution](https://github.com/pycalphad/pycalphad/commit/06f5df08579862b5adcb80c219bacb5137fe717a) for TODO 2, but a little bit hack :(

**Comment by zhusee2** [comment]
OK Todo 1 seems to be solved with `npm config`

**Comment by zhusee2** [comment]
@cjies I took a look at the solution,  unfortunately our `lerna` command did exited with 0. XD
I guess we can ignore Todo 2 for now once Todo 1 is solved, or we can try the old `|| exit 1` trick

```
The command "if [ ${TRAVIS_PULL_REQUEST} = 'false' ]; then yarn canary ; fi" exited with 0.
```

**Comment by cjies** [comment]
Quite weird... ☹️
